version: '3'
services:
  ${CIRCLE_PROJECT_REPONAME}:
    image: nginx
    volumes:
      - /home/ubuntu/conf.d:/etc/nginx/conf.d
      - /home/ubuntu/ssl/:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
